# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate absolute error regression loss.
#'
#' @param y_true Ground truth (correct) target values.
#' @param y_pred Estimated target values.
#' @return  A numeric vector of length equal to \code{max(length(y_true), length(y_pred))}.
#' @export
absolute_error <- function(y_true, y_pred) {
    .Call('scorer_absolute_error', PACKAGE = 'scorer', y_true, y_pred)
}

#' Calculate percent error regression loss.
#'
#' @param y_true Ground truth (correct) target values.
#' @param y_pred Estimated target values.
#' @return  A numeric vector of length equal to \code{max(length(y_true), length(y_pred))}.
#' @export
percent_error <- function(y_true, y_pred) {
    .Call('scorer_percent_error', PACKAGE = 'scorer', y_true, y_pred)
}

#' Calculate absolute percent error regression loss.
#'
#' @param y_true Ground truth (correct) target values.
#' @param y_pred Estimated target values.
#' @return  A numeric vector of length equal to \code{max(length(y_true), length(y_pred))}.
#' @export
absolute_percent_error <- function(y_true, y_pred) {
    .Call('scorer_absolute_percent_error', PACKAGE = 'scorer', y_true, y_pred)
}

#' Calculate squared error regression loss.
#'
#' @param y_true Ground truth (correct) target values.
#' @param y_pred Estimated target values.
#' @return  A numeric vector of length equal to \code{max(length(y_true), length(y_pred))}.
#' @export
squared_error <- function(y_true, y_pred) {
    .Call('scorer_squared_error', PACKAGE = 'scorer', y_true, y_pred)
}

#' Calculate mean error regression loss.
#'
#' @param y_true Ground truth (correct) target values.
#' @param y_pred Estimated target values.
#' @return  A numeric vector of length equal to \code{max(length(y_true), length(y_pred))}.
#' @export
mean_error <- function(y_true, y_pred) {
    .Call('scorer_mean_error', PACKAGE = 'scorer', y_true, y_pred)
}

#' Calculate mean absolute error regression loss.
#'
#' @param y_true Ground truth (correct) target values.
#' @param y_pred Estimated target values.
#' @return  A numeric vector of length equal to \code{max(length(y_true), length(y_pred))}.
#' @export
mean_absolute_error <- function(y_true, y_pred) {
    .Call('scorer_mean_absolute_error', PACKAGE = 'scorer', y_true, y_pred)
}

