# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

median_rcpp <- function(x) {
    .Call('scorer_median_rcpp', PACKAGE = 'scorer', x)
}

absolute_error_rcpp <- function(y_true, y_pred) {
    .Call('scorer_absolute_error_rcpp', PACKAGE = 'scorer', y_true, y_pred)
}

#' Calculate percent error regression loss.
#'
#' @param y_true Ground truth (correct) target values.
#' @param y_pred Estimated target values.
#' @return  A numeric vector of length equal to \code{max(length(y_true), length(y_pred))}.
#' @export
percent_error <- function(y_true, y_pred) {
    .Call('scorer_percent_error', PACKAGE = 'scorer', y_true, y_pred)
}

#' Calculate absolute percent error regression loss.
#'
#' @param y_true Ground truth (correct) target values.
#' @param y_pred Estimated target values.
#' @return  A numeric vector of length equal to \code{max(length(y_true), length(y_pred))}.
#' @export
absolute_percent_error <- function(y_true, y_pred) {
    .Call('scorer_absolute_percent_error', PACKAGE = 'scorer', y_true, y_pred)
}

#' Calculate squared error regression loss.
#'
#' @param y_true Ground truth (correct) target values.
#' @param y_pred Estimated target values.
#' @return  A numeric vector of length equal to \code{max(length(y_true), length(y_pred))}.
#' @export
squared_error <- function(y_true, y_pred) {
    .Call('scorer_squared_error', PACKAGE = 'scorer', y_true, y_pred)
}

#' Calculate mean error regression loss.
#'
#' @param y_true Ground truth (correct) target values.
#' @param y_pred Estimated target values.
#' @return  A numeric vector of length one.
#' @export
mean_error <- function(y_true, y_pred) {
    .Call('scorer_mean_error', PACKAGE = 'scorer', y_true, y_pred)
}

#' Calculate mean absolute error regression loss.
#'
#' @param y_true Ground truth (correct) target values.
#' @param y_pred Estimated target values.
#' @return  A numeric vector of length one.
#' @export
mean_absolute_error_rcpp <- function(y_true, y_pred) {
    .Call('scorer_mean_absolute_error_rcpp', PACKAGE = 'scorer', y_true, y_pred)
}

#' Calculate median absolute error regression loss.
#'
#' @param y_true Ground truth (correct) target values.
#' @param y_pred Estimated target values.
#' @return  A numeric vector of length one.
#' @export
median_absolute_error_rcpp <- function(y_true, y_pred) {
    .Call('scorer_median_absolute_error_rcpp', PACKAGE = 'scorer', y_true, y_pred)
}

#' Calculate mean percent error regression loss.
#'
#' @param y_true Ground truth (correct) target values.
#' @param y_pred Estimated target values.
#' @return  A numeric vector of length one.
#' @export
mean_percent_error <- function(y_true, y_pred) {
    .Call('scorer_mean_percent_error', PACKAGE = 'scorer', y_true, y_pred)
}

#' Calculate median percent error regression loss.
#'
#' @param y_true Ground truth (correct) target values.
#' @param y_pred Estimated target values.
#' @return  A numeric vector of length one.
#' @export
median_percent_error <- function(y_true, y_pred) {
    .Call('scorer_median_percent_error', PACKAGE = 'scorer', y_true, y_pred)
}

#' Calculate mean squared error regression loss.
#'
#' @param y_true Ground truth (correct) target values.
#' @param y_pred Estimated target values.
#' @return  A numeric vector of length one.
#' @export
mean_squared_error <- function(y_true, y_pred) {
    .Call('scorer_mean_squared_error', PACKAGE = 'scorer', y_true, y_pred)
}

#' Calculate median squared error regression loss.
#'
#' @param y_true Ground truth (correct) target values.
#' @param y_pred Estimated target values.
#' @return  A numeric vector of length one.
#' @export
median_squared_error <- function(y_true, y_pred) {
    .Call('scorer_median_squared_error', PACKAGE = 'scorer', y_true, y_pred)
}

#' Calculate mean absolute percent error regression loss.
#'
#' @param y_true Ground truth (correct) target values.
#' @param y_pred Estimated target values.
#' @return  A numeric vector of length one.
#' @export
mean_absolute_percent_error <- function(y_true, y_pred) {
    .Call('scorer_mean_absolute_percent_error', PACKAGE = 'scorer', y_true, y_pred)
}

#' Calculate median absolute percent error regression loss.
#'
#' @param y_true Ground truth (correct) target values.
#' @param y_pred Estimated target values.
#' @return  A numeric vector of length one.
#' @export
median_absolute_percent_error <- function(y_true, y_pred) {
    .Call('scorer_median_absolute_percent_error', PACKAGE = 'scorer', y_true, y_pred)
}

