# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate mean absolute error between actual and forecast.
#'
#' \code{mae} takes actual and forecast numeric vectors and returns a
#' numeric vector where forecast is subtracted from the actual, the
#' absolute value is taken of those errors, and lastly, the mean is
#' taken of those absolute erros.
#'
#' @param actual a numeric vector of actuals.
#' @param forecast a numeric vector of forecasts.
#' @return  a numeric vector of length one representing the mean of absolute errors.
#' @examples
#' # Examples
#' mae(1:100, 100:1)
#' @export
mae <- function(actual, forecast) {
    .Call('scorer_mae', PACKAGE = 'scorer', actual, forecast)
}

